<form method="post">
    <div class="inner-inputs">
        <label for="username">Username <strong>*</strong></label>
        <br>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Password <strong>*</strong></label>
        <br>
        <input type="password" id="password" name="password" required>
        <br>
        <input type="submit" value="Login">
    </div>
</form>