<nav>
    <ul>
        <?php
       $db = mysqli_connect("sql102.epizy.com", "epiz_31786048", "EbTuI6yBml6gYN9", "epiz_31786048_project_wea_das"); 
        mysqli_set_charset($db,"utf8");
        $genres_query = "SELECT * FROM tx_genres";
        $genres_result = mysqli_query($db, $genres_query);
        $genres = mysqli_fetch_all($genres_result, MYSQLI_ASSOC);
        foreach ($genres as $genre){
            $file = strtolower($genre["name"]);
            echo "<li>"."<a href=$file class='a-'>". $genre["name"] . "</a>" . "</li>";
        }
        ?>
    </ul>
</nav>